### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by rohan-bhatia** [rohan-bhatia/coinspot-scraper#1]
IndexError: list index out of range error is URL is not found

**Comment by rohan-bhatia** [comment]
Traceback (most recent call last):
  File "D:\Projects\eclipse\Coinspot\scraper\coinspot.py", line 58, in <module>
    priceStringFull = soup.select('h1.price-title')[0].text.strip()
IndexError: list index out of range

**Comment by rohan-bhatia** [comment]
``Traceback (most recent call last):
  File "D:\Dropbox\Personal Documents\Rohan Bhatia\Projects\eclipse\Coinspot\scraper\coinspot.py", line 58, in <module>
    priceStringFull = soup.select('h1.price-title')[0].text.strip()
IndexError: list index out of range``

**Comment by rohan-bhatia** [comment]
```python
Traceback (most recent call last): File "D:\Dropbox\Personal Documents\Rohan Bhatia\Projects\eclipse\Coinspot\scraper\coinspot.py", line 58, in <module>
priceStringFull = soup.select('h1.price-title')[0].text.strip()
IndexError: list index out of range
```

**Comment by rohan-bhatia** [comment]
Turns out coinspot are just using a page with Not found on it.

Had to write a check for the string
```python
if(soup.text != "Not Found"):
    priceStringFull = soup.select('h1.price-title')[0].text.strip()
```
